Add stoud check for main tests
oamg/leapp-insights-tasks pull request #10
Opened 2024-01-24 12:55 UTC by Monnte

OAMG-10421

2024-01-25 09:33 UTC, andywaltlova requested changes
Good start! I would expect to test main for all possible `raise ProcessError` in script - failed leapp install/other pkg.

I would probably also check if alert is true or false based on what is expected for each output message.

2024-02-02 16:50 UTC, andywaltlova commented on tests/test_main.py
> +    print(captured.out)
```suggestion
```

2024-02-06 14:03 UTC, Monnte commented on tests/test_main.py
> +    print(captured.out)
removed.

2024-02-06 14:15 UTC, andywaltlova approved these changes

2024-02-06 14:15 UTC, merged